app:
  og:
    url: https://ok.surf/
spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
news:
  api:
    url: https://ok.surf/api/v1/
    rate: 60000

server:
  port: 8093
