server:
  port: 8092
app:
  binance:
    websocket:
      reconnection:
        delay: 10_000
      url: wss://stream.binance.com:9443/ws/btcusdt@trade
  frontend:
    rate: 5_000
    path: /topic/btcusdt